<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\CourseEducationLevel;
use App\Models\CourseParticipant;
use App\Models\EducationLevel;
use App\Models\Topic;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class BackupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::beginTransaction();

        // Seed courses
        $courses = [
            [
                'id' => '1',
                'topic_id' => '0',
                'title' => 'Sehat dan Bahagia dalam Kehamilan: Pengetahuan Dasar untuk Ibu Hamil',
                'slug' => 'sehat-dan-bahagia-dalam-kehamilan-pengetahuan-dasar-untuk-ibu-hamil',
                'description' => 'Seminar ini bertujuan untuk memberikan pemahaman mendalam kepada peserta mengenai kesehatan reproduksi dan kehamilan wanita. Peserta akan mempelajari berbagai tahap perkembangan janin, nutrisi yang dibutuhkan selama kehamilan, serta bagaimana menjaga kesehatan fisik dan mental selama masa kehamilan. Selain itu, seminar ini juga akan membahas persiapan persalinan dan tips menjaga kesehatan pasca melahirkan. Dengan mengikuti seminar ini, peserta diharapkan dapat lebih siap dalam menjalani proses kehamilan dengan pengetahuan yang memadai.',
                'date' => '2024-09-16',
                'start_time' => '09:00:00',
                'quota' => '24',
                'zoom_link' => 'https://zoom.us/j/1234567890',
                'zoom_id' => '123 4567 890',
                'zoom_password' => '123456',
                'youtube_link' => 'https://www.youtube.com/watch?v=4ZAHX-N-AhM',
                'status' => Course::STATUS_AVAILABLE,
                'lecturer_id' => '3',
                'created_at' => '2024-09-16 09:02:45',
                'updated_at' => '2024-09-16 09:31:44',
                'deleted_at' => null,
                'created_by' => '3',
                'updated_by' => '3',
                'deleted_by' => null,
            ],
            [
                'id' => '2',
                'topic_id' => '0',
                'title' => 'tes',
                'slug' => 'tes',
                'description' => 'tes',
                'date' => '2024-09-21',
                'start_time' => '10:12:00',
                'quota' => '20',
                'zoom_link' => 'hs',
                'zoom_id' => '67',
                'zoom_password' => '51',
                'youtube_link' => null,
                'status' => Course::STATUS_AVAILABLE,
                'lecturer_id' => '8',
                'created_at' => '2024-09-19 10:12:14',
                'updated_at' => '2024-09-19 10:12:14',
                'deleted_at' => null,
                'created_by' => '8',
                'updated_by' => '8',
                'deleted_by' => null,
            ],
            [
                'id' => '3',
                'topic_id' => '0',
                'title' => 'Probiotik pada Bacterial Vaginosis, Mitos atau Fakta?',
                'slug' => 'probiotik-pada-bacterial-vaginosis-mitos-atau-fakta',
                'description' => 'Membahasa peran probitoik pada BV.',
                'date' => '2024-09-25',
                'start_time' => '10:00:00',
                'quota' => '200',
                'zoom_link' => 'https://us02web.zoom.us/webinar/register/WN_c9EiZ1nhQxOg8a55EX5oSw',
                'zoom_id' => '84861724046',
                'zoom_password' => '867771',
                'youtube_link' => null,
                'status' => Course::STATUS_AVAILABLE,
                'lecturer_id' => '8',
                'created_at' => '2024-09-23 12:16:11',
                'updated_at' => '2024-09-23 12:16:11',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '2',
                'deleted_by' => null,
            ],
            [
                'id' => '4',
                'topic_id' => '0',
                'title' => 'Peranan HPV DNA pada modalitas skrining kanker serviks',
                'slug' => 'peranan-hpv-dna-pada-modalitas-skrining-kanker-serviks',
                'description' => 'Kuliah ini membahas mengenai modalitas pemeriksaan DNA HPV dalam deteksi dini lesi prakanker serviks di Indonesia',
                'date' => '2024-09-24',
                'start_time' => '13:00:00',
                'quota' => '30',
                'zoom_link' => 'https://us02web.zoom.us/webinar/register/WN_c9EiZ1nhQxOg8a55EX5oSw',
                'zoom_id' => '88768888029',
                'zoom_password' => '12345',
                'youtube_link' => null,
                'status' => Course::STATUS_AVAILABLE,
                'lecturer_id' => '112',
                'created_at' => '2024-09-23 12:27:25',
                'updated_at' => '2024-09-23 12:27:25',
                'deleted_at' => null,
                'created_by' => '112',
                'updated_by' => '112',
                'deleted_by' => null,
            ],
            [
                'id' => '5',
                'topic_id' => '0',
                'title' => 'Kemoterapi Pada Kanker Endometrium',
                'slug' => 'kemoterapi-pada-kanker-endometrium',
                'description' => 'Menjelaskan tentang kemoterapi',
                'date' => '2024-11-05',
                'start_time' => '10:00:00',
                'quota' => '100',
                'zoom_link' => 'https://us02web.zoom.us/j/89084808790?pwd=lbiBbTIByQmglLiRgbxteQAo5ITSRz.1',
                'zoom_id' => ' 890 8480 8790',
                'zoom_password' => '049266',
                'youtube_link' => null,
                'status' => Course::STATUS_AVAILABLE,
                'lecturer_id' => '82',
                'created_at' => '2024-10-29 09:50:02',
                'updated_at' => '2024-10-29 09:50:02',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '2',
                'deleted_by' => null,
            ],
            [
                'id' => '6',
                'topic_id' => '2',
                'title' => 'Peran Radioterapi pada Kanker serviks',
                'slug' => 'peran-radioterapi-pada-kanker-serviks',
                'description' => 'Menjelaskan tentang radioterapi',
                'date' => '2024-12-25',
                'start_time' => '11:00:00',
                'quota' => '50',
                'zoom_link' => 'https://us02web.zoom.us/j/89084808790?pwd=lbiBbTIByQmglLiRgbxteQAo5ITSRz.1 Jam 10',
                'zoom_id' => '12344567',
                'zoom_password' => 'asdggh',
                'youtube_link' => null,
                'status' => Course::STATUS_AVAILABLE,
                'lecturer_id' => '112',
                'created_at' => '2024-10-31 10:19:56',
                'updated_at' => '2024-12-25 22:43:48',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '112',
                'deleted_by' => null,
            ],
        ];

        foreach ($courses as $course) {
            Course::create($course);
        }

        // Seed course education levels
        $courseEducationLevels = [
            [
                'id' => '4',
                'course_id' => '1',
                'education_level_id' => '1',
                'created_at' => '2024-09-16 09:31:44',
                'updated_at' => '2024-09-16 09:31:44',
                'deleted_at' => null,
                'created_by' => '3',
                'updated_by' => '3',
                'deleted_by' => null,
            ],
            [
                'id' => '5',
                'course_id' => '1',
                'education_level_id' => '2',
                'created_at' => '2024-09-16 09:31:44',
                'updated_at' => '2024-09-16 09:31:44',
                'deleted_at' => null,
                'created_by' => '3',
                'updated_by' => '3',
                'deleted_by' => null,
            ],
            [
                'id' => '6',
                'course_id' => '2',
                'education_level_id' => '6',
                'created_at' => '2024-09-19 10:12:14',
                'updated_at' => '2024-09-19 10:12:14',
                'deleted_at' => null,
                'created_by' => '8',
                'updated_by' => '8',
                'deleted_by' => null,
            ],
            [
                'id' => '7',
                'course_id' => '3',
                'education_level_id' => '5',
                'created_at' => '2024-09-23 12:16:11',
                'updated_at' => '2024-09-23 12:16:11',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '2',
                'deleted_by' => null,
            ],
            [
                'id' => '8',
                'course_id' => '3',
                'education_level_id' => '6',
                'created_at' => '2024-09-23 12:16:11',
                'updated_at' => '2024-09-23 12:16:11',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '2',
                'deleted_by' => null,
            ],
            [
                'id' => '9',
                'course_id' => '3',
                'education_level_id' => '7',
                'created_at' => '2024-09-23 12:16:11',
                'updated_at' => '2024-09-23 12:16:11',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '2',
                'deleted_by' => null,
            ],
            [
                'id' => '10',
                'course_id' => '4',
                'education_level_id' => '5',
                'created_at' => '2024-09-23 12:27:25',
                'updated_at' => '2024-09-23 12:27:25',
                'deleted_at' => null,
                'created_by' => '112',
                'updated_by' => '112',
                'deleted_by' => null,
            ],
            [
                'id' => '11',
                'course_id' => '4',
                'education_level_id' => '4',
                'created_at' => '2024-09-23 12:27:25',
                'updated_at' => '2024-09-23 12:27:25',
                'deleted_at' => null,
                'created_by' => '112',
                'updated_by' => '112',
                'deleted_by' => null,
            ],
            [
                'id' => '12',
                'course_id' => '4',
                'education_level_id' => '6',
                'created_at' => '2024-09-23 12:27:25',
                'updated_at' => '2024-09-23 12:27:25',
                'deleted_at' => null,
                'created_by' => '112',
                'updated_by' => '112',
                'deleted_by' => null,
            ],
            [
                'id' => '13',
                'course_id' => '5',
                'education_level_id' => '7',
                'created_at' => '2024-10-29 09:50:02',
                'updated_at' => '2024-10-29 09:50:02',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '2',
                'deleted_by' => null,
            ],
            [
                'id' => '16',
                'course_id' => '6',
                'education_level_id' => '6',
                'created_at' => '2024-12-25 22:43:48',
                'updated_at' => '2024-12-25 22:43:48',
                'deleted_at' => null,
                'created_by' => '112',
                'updated_by' => '112',
                'deleted_by' => null,
            ],
            [
                'id' => '17',
                'course_id' => '6',
                'education_level_id' => '7',
                'created_at' => '2024-12-25 22:43:48',
                'updated_at' => '2024-12-25 22:43:48',
                'deleted_at' => null,
                'created_by' => '112',
                'updated_by' => '112',
                'deleted_by' => null,
            ],
        ];

        foreach ($courseEducationLevels as $courseEducationLevel) {
            CourseEducationLevel::create($courseEducationLevel);
        }

        // Seed course participants
        $courseParticipants = [
            [
                'id' => '2',
                'participant_id' => '12',
                'course_id' => '4',
                'created_at' => '2024-10-29 08:29:56',
                'updated_at' => '2024-10-29 08:29:56',
                'deleted_at' => null,
                'created_by' => '12',
                'updated_by' => '12',
                'deleted_by' => null,
            ],
            [
                'id' => '3',
                'participant_id' => '12',
                'course_id' => '2',
                'created_at' => '2024-10-29 09:31:45',
                'updated_at' => '2024-10-29 09:31:45',
                'deleted_at' => null,
                'created_by' => '12',
                'updated_by' => '12',
                'deleted_by' => null,
            ],
            [
                'id' => '4',
                'participant_id' => '12',
                'course_id' => '1',
                'created_at' => '2024-10-29 09:35:37',
                'updated_at' => '2024-10-29 09:35:37',
                'deleted_at' => null,
                'created_by' => '12',
                'updated_by' => '12',
                'deleted_by' => null,
            ],
            [
                'id' => '5',
                'participant_id' => '11',
                'course_id' => '6',
                'created_at' => '2025-01-05 09:19:48',
                'updated_at' => '2025-01-05 09:19:48',
                'deleted_at' => null,
                'created_by' => '11',
                'updated_by' => '11',
                'deleted_by' => null,
            ],
        ];

        foreach ($courseParticipants as $courseParticipant) {
            CourseParticipant::create($courseParticipant);
        }

        // Seed education levels
        $educationLevels = [
            [
                'id' => '1',
                'name' => 'S1',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
            ],
            [
                'id' => '2',
                'name' => 'S2',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
            ],
            [
                'id' => '3',
                'name' => 'S3',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
            ],
            [
                'id' => '4',
                'name' => 'Dokter Muda',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
            ],
            [
                'id' => '5',
                'name' => 'Dokter Umum',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
            ],
            [
                'id' => '6',
                'name' => 'Pendidikan Sp1',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
            ],
            [
                'id' => '7',
                'name' => 'Pendidikan Sp2',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
            ],
            [
                'id' => '8',
                'name' => 'S1 Kebidanan',
                'created_at' => '2024-09-17 08:49:52',
                'updated_at' => '2024-09-17 08:49:52',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '2',
                'deleted_by' => null,
            ],
        ];

        foreach ($educationLevels as $educationLevel) {
            EducationLevel::create($educationLevel);
        }

        // Seed users
        $users = [
            [
                'id' => '1',
                'name' => 'Prayogo Hardiansyah',
                'nik' => '1766511029034732',
                'photo' => null,
                'phone' => '0903 0451 725',
                'address' => 'Psr. Sutami No. 539, Administrasi Jakarta Timur 62008, Papua',
                'institution' => null,
                'cv' => 'Ad aliquid laboriosam consectetur. Cumque atque nam voluptatem vero ipsum dolorem. Sint et voluptatem alias ex nostrum voluptas. Sed laboriosam in eum aperiam consequatur.',
                'email' => 'developer@mail.com',
                'email_verified_at' => '2024-09-16 07:49:57',
                'google_id' => '0bce8d1f-1b72-3667-a6ed-e60bac3d08d0',
                'password' => '$2y$12$I8Yd.NNHPcyI2Wo5pYu7UOaewgfOLm9kzX0/s/XXKDXZ0Img15EkW',
                'remember_token' => 'Ys0twyEZo9',
                'created_at' => '2024-09-16 07:49:57',
                'updated_at' => '2024-09-16 07:49:57',
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '2',
                'name' => 'Elisa Silvia Andriani S.Pd',
                'nik' => '2766740247112172',
                'photo' => null,
                'phone' => '(+62) 22 4479',
                'address' => 'Dk. Rajawali Barat No. 210, Salatiga 92111, Sulut',
                'institution' => null,
                'cv' => 'Sapiente odit impedit modi. Perferendis nisi et doloremque doloremque. Voluptatum officiis rerum necessitatibus fugiat minus quos. Ut perspiciatis dolorum dolorem aliquid.',
                'email' => 'admin@mail.com',
                'email_verified_at' => '2024-09-16 07:49:57',
                'google_id' => '45ba0823-377e-352c-95e7-39a50fb5fbde',
                'password' => '$2y$12$8d66OhQSV1otF8y90uxDFurPg9Eft8dvSYWG5LhK0NGB2Y8UUTsGu',
                'remember_token' => 'LHHKNQmWD5xhZSzsIJzgq7pVptmr6AhQLWhmkcIUeTR0WekFqZuuEv4hOP4N',
                'created_at' => '2024-09-16 07:49:57',
                'updated_at' => '2024-09-16 07:49:57',
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => '2',
                'deleted_by' => null,
                'education_level_id' => '1',
                'is_verified' => '1',
            ],
            [
                'id' => '3',
                'name' => 'Ikhbar Nurinsani',
                'nik' => '1930511022',
                'photo' => null,
                'phone' => '+628881688055',
                'address' => 'Jl.Otista Cijangkar Gg.Kharya Bhakti Rt.04/02',
                'institution' => 'UMMI',
                'cv' => null,
                'email' => 'ikhbarnuri.dev@gmail.com',
                'email_verified_at' => '2024-09-16 08:30:00',
                'google_id' => '117811306934823882060',
                'password' => null,
                'remember_token' => 'DsGKuRBjqL8xkTRUdqX8iaIzVEQflGogYbYvnnwF5bOs6vePiOliZKfBHGHE',
                'created_at' => '2024-09-16 08:30:00',
                'updated_at' => '2024-09-16 08:30:33',
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => '3',
                'deleted_by' => null,
                'education_level_id' => '1',
                'is_verified' => '1',
            ],
            [
                'id' => '8',
                'name' => 'Pandu Habibie',
                'nik' => '198511032019031006',
                'photo' => null,
                'phone' => '082131243200',
                'address' => 'GAYUNGSARI TIMUR II BLOK MGF NO.1 RT 002 RW 006 SURABAYA',
                'institution' => 'fk unair',
                'cv' => null,
                'email' => 'panduhabibie@gmail.com',
                'email_verified_at' => '2024-09-19 10:10:46',
                'google_id' => '100051429339374343076',
                'password' => null,
                'remember_token' => 'kc52zqYGiHEnCDAolgnMZxXct8dUDwNkkb8ans4K8ETwiD402EPreM98Jde6',
                'created_at' => '2024-09-19 10:10:46',
                'updated_at' => '2024-09-19 10:11:23',
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => '8',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '11',
                'name' => 'Pranowo Saptadi',
                'nik' => '3171081609700004',
                'photo' => null,
                'phone' => '081288857363',
                'address' => 'Cibubur',
                'institution' => 'TFC',
                'cv' => null,
                'is_verified' => '0',
                'education_level_id' => '7',
                'email' => 'pranowo.tfc@gmail.com',
                'email_verified_at' => '2025-01-08 08:21:44',
                'google_id' => null,
                'password' => '$2y$12$2zGgQbycs5i33PQdYRAZG.G2S5LiqHIn6d5vAtWui7UZiuU3EkyGG',
                'remember_token' => null,
                'created_at' => '2025-01-08 08:16:47',
                'updated_at' => '2025-01-08 08:23:33',
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => '9',
                'deleted_by' => null,
            ],
            [
                'id' => '12',
                'name' => 'M. Dimas Abdi Putra',
                'nik' => '3578071803880003',
                'photo' => null,
                'phone' => '085335888046',
                'address' => 'Kacapiring 18, Surabaya',
                'institution' => 'RSUD dr. Soetomo',
                'cv' => null,
                'email' => 'm.dimas.ap@gmail.com',
                'email_verified_at' => '2024-09-20 11:03:21',
                'google_id' => null,
                'password' => '$2y$12$hIkW57BDR7uROi./QUejCOuEdASpzTUVYMgbRD/dXSzAf5bty6flm',
                'remember_token' => '1WnXyr6qKJLz8hldNBO8dT2blOs8MYvq0BUpqtWl41iGMAw0LiHp4bB60gwP',
                'created_at' => '2024-09-20 11:02:51',
                'updated_at' => '2024-09-20 11:03:21',
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => '12',
                'deleted_by' => null,
                'education_level_id' => '7',
                'is_verified' => '1',
            ],
            [
                'id' => '13',
                'name' => 'dr. M. ARI BUDI PERDANA',
                'nik' => '3507151911950002',
                'photo' => null,
                'phone' => '081217565212',
                'address' => 'Jl. Empu Barada No.06 RT 004/RW 009 Kelurahan Kepanjen, Kecamatan Jombang, Kabupaten Jombang',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'aribudi95@gmail.com',
                'email_verified_at' => '2024-09-20 11:16:26',
                'google_id' => null,
                'password' => '$2y$12$e8/wjsJluQzvQhE45JNgyeSLUMEpWTun0BG/W5Gt0z8qFZhwIJ3JS',
                'remember_token' => '7fO2Hy33BWz4nhmO3yLGhRmD1mGVbNL3fV2pIZGIpha4ikcbEOOFHGU3Ojzm',
                'created_at' => '2024-09-20 11:15:45',
                'updated_at' => '2024-09-20 11:16:26',
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => '13',
                'deleted_by' => null,
                'education_level_id' => '5',
                'is_verified' => '1',
            ],
            [
                'id' => '68',
                'name' => 'M. Dikman Angsar',
                'nik' => '130287008',
                'photo' => 'user/photo/2OehNAlsE0ELAAB7FRnlNxTpiSujcOWGZG4WjLsH.png',
                'phone' => '0811311360',
                'address' => 'Jemursari Utara V/8 RT 003/RW 008 Kelurahan Jemur Wonosari Kecamatan Wonocolo Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'dikmanangsar@gmail.com',
                'email_verified_at' => '2024-09-24 06:49:09',
                'google_id' => null,
                'password' => '$2y$12$QaHQ4I8/jnQlyPkFjsCyoOQdqfb4tRoANCZqwlqLRrdtw8cvt4kB.',
                'remember_token' => null,
                'created_at' => '2024-09-24 06:37:57',
                'updated_at' => '2024-11-25 03:51:04',
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => '10',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '69',
                'name' => 'Lila Dewata',
                'nik' => '130287009',
                'photo' => 'user/photo/fYqfypJwwYER3pSQpHPl2050Or5buByI3gyGttEf.png',
                'phone' => '0816524109',
                'address' => 'Galaxi Bumi Permai Blok A-2/11 RT 001/RW 009 Kelurahan Keputih, Kecamatan Sukolilo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'muruze32@yahoo.com',
                'email_verified_at' => '2024-09-24 06:49:14',
                'google_id' => null,
                'password' => '$2y$12$hh0DzLmBKYxRA1hDn9s5uun0ZxAoedxIfc1UatcimNXPkUJkyiZZO',
                'remember_token' => null,
                'created_at' => '2024-09-24 06:42:37',
                'updated_at' => '2024-11-25 03:52:20',
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => '11',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '70',
                'name' => 'Samsulhadi',
                'nik' => '130355347',
                'photo' => 'user/photo/HL7qrtpouvmBcEsN2UvXMNI28e1PtGcjO3ijRLEs.png',
                'phone' => '0811336616',
                'address' => 'Ngagel Tama 72-74 RT 004/RW 001 Kelurahan Pucangsewu, Kecamatan Gubeng, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'batabsby@yahoo.com',
                'email_verified_at' => '2024-09-24 06:49:17',
                'google_id' => null,
                'password' => '$2y$12$fFkm2370sbenoRwl2fGzn.iAs/OIxFd2HnrU3HB/c7EwctrVtSn/e',
                'remember_token' => null,
                'created_at' => '2024-09-24 06:46:25',
                'updated_at' => '2024-11-25 03:59:37',
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => '12',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '71',
                'name' => 'Soehartono',
                'nik' => '194610291974021001',
                'photo' => 'user/photo/DFYi8hCJnkjKn2eeInplYKQH2AFLFG8rc4Q8fb74.png',
                'phone' => '0811347720',
                'address' => 'Jemursari RT 002/ RW 010 Kelurahan Jemur Wonosari, Kecamatan Wonocolo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'batabsby1@yahoo.com',
                'email_verified_at' => '2024-09-25 02:46:13',
                'google_id' => null,
                'password' => '$2y$12$j.1BjReyAcRfyoyRvJYWh.uCJ7QM22Iya62Rm/lemiqqEe.F.DLSi',
                'remember_token' => null,
                'created_at' => '2024-09-25 02:30:01',
                'updated_at' => '2024-11-25 04:05:00',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '13',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '72',
                'name' => 'Sunjoto',
                'nik' => '194811201977031001',
                'photo' => 'user/photo/gOGeXrWFul56m09aAZtlHE98C0Ar32UoSPmPTmTX.png',
                'phone' => '082317000060',
                'address' => 'Karanggayam No.38 RT 001/RW 003 Kelurahan Tambaksari, Kec. Tambaksari, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'onkogin.surabaya@gmail.com',
                'email_verified_at' => '2024-09-25 02:46:17',
                'google_id' => null,
                'password' => '$2y$12$stvz7NcGTubWvTdxXH82Te3XErPSH2qV8XcFXa71Od4UlP5tFu/Vq',
                'remember_token' => null,
                'created_at' => '2024-09-25 02:35:45',
                'updated_at' => '2024-11-25 05:14:04',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '112',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '73',
                'name' => 'Erry Gumilar Dahlan',
                'nik' => '194908131978111001',
                'photo' => 'user/photo/ASqKy0cL3TCWiHZkA3o9bUp4F2mWS8kn38FAqUYQ.png',
                'phone' => '0818509014',
                'address' => 'Bukit Pakis Utara 3/T.A.16 RT 001/ RW 007 Kel. Dukuh Pakis, Kec. Dukuh Pakis, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'errygumilar@gmail.com',
                'email_verified_at' => '2024-09-25 02:46:21',
                'google_id' => null,
                'password' => '$2y$12$rggRHR/c.vtxZfGGpJe/Le.O8zdzKRcYzI6WOdjl90hvQKt7DFP6G',
                'remember_token' => null,
                'created_at' => '2024-09-25 02:37:54',
                'updated_at' => '2024-11-26 04:08:20',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '82',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '74',
                'name' => 'Poedjo Hartono',
                'nik' => '195503281982031009',
                'photo' => 'user/photo/wVonlOTl79Bp4vAjDesbibJ4cBWZRvSxAuFzq3LZ.png',
                'phone' => '0811319905',
                'address' => 'Dharmahusada Indah A/28 RT 007/ RW 004, Kel. Mojo, Kec. Gubeng, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'poedjoh@gmail.com',
                'email_verified_at' => '2024-09-25 02:46:25',
                'google_id' => null,
                'password' => '$2y$12$MYgiL/qxOexKiDG9oRYVEOMcKBro458gonuNZoMdF.ZLYIJFUKChO',
                'remember_token' => null,
                'created_at' => '2024-09-25 02:45:28',
                'updated_at' => '2024-11-26 04:09:10',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '16',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '75',
                'name' => 'Hari Paraton',
                'nik' => '3578020105540004',
                'photo' => 'user/photo/gdEfqOWAIi0TT9dS941n3Nnhdku0VKpZ2E1FhRFu.png',
                'phone' => '081216543254',
                'address' => 'Sidosermo 5/10 RT 002/ RW 005 Kel. Sidosermo, Kec. Wonocolo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'hparathon1954@gmail.com',
                'email_verified_at' => '2024-09-25 06:22:06',
                'google_id' => null,
                'password' => '$2y$12$vIyg8xAUZBLb1hcpRIQlVuGkyXLQJFMdz0m/JWYOq5ncv3C78UesK',
                'remember_token' => null,
                'created_at' => '2024-09-25 06:03:38',
                'updated_at' => '2024-11-26 04:14:31',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '17',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '76',
                'name' => 'Hermanto Tri Joewono',
                'nik' => '3578262701560002',
                'photo' => 'user/photo/3dXBQuMWMcrtIolxGA2xYt8K3B0R5r7ZqDK2UyQF.png',
                'phone' => '085648277764',
                'address' => 'Kalijudan Indah Blok 1/4-B RT 002/ RW 007, Kel. Kalijudan, Kec. Mulyorejo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'hermanto.tri@fk.unair.ac.id',
                'email_verified_at' => '2024-09-25 06:22:10',
                'google_id' => null,
                'password' => '$2y$12$sOSEDQJN21TtY2huw8/9n.a76VSw9qRobPh5LLRaBRo9ARVELHmNy',
                'remember_token' => null,
                'created_at' => '2024-09-25 06:21:58',
                'updated_at' => '2024-11-26 04:15:51',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '18',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '77',
                'name' => 'Aditiawarman',
                'nik' => '3578090111580001',
                'photo' => 'user/photo/YaOJR3ywjQPMioviVNh0EPHJGJJtJKw1sflKizFI.png',
                'phone' => '08123005116',
                'address' => 'Galaxi Klampis Asri Selt 3/58 RT 001/RW 009 Kel. Medokan Semampir, Kec. Sukolilo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'aditia60117@gmail.com',
                'email_verified_at' => '2024-09-26 06:45:55',
                'google_id' => null,
                'password' => '$2y$12$yy9dGRt8Y/sTRaNGeqYxr.KcXkvq/D3dcgKpxfF19DCmHiJteB18u',
                'remember_token' => null,
                'created_at' => '2024-09-26 06:31:34',
                'updated_at' => '2024-11-26 04:25:25',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '19',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '78',
                'name' => 'Hendy Hendarto',
                'nik' => '3578051708610003',
                'photo' => 'user/photo/hTle58Ut6iMj5ZzyvS6EWElmWp3dzwYd6tnvLq7K.png',
                'phone' => '08123007080',
                'address' => 'Bintoro 15 RT 005/RW 014 Kel. Dr. Sutomo, Kec. Tegalsari, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'hndhendy@yahoo.com',
                'email_verified_at' => '2024-09-26 06:45:58',
                'google_id' => null,
                'password' => '$2y$12$9CVwM2FyiyAwOMPUzo6G3e2weodJUtfxGvE5ke58lZxjgE2RzhxMq',
                'remember_token' => null,
                'created_at' => '2024-09-26 06:39:55',
                'updated_at' => '2024-11-28 01:42:12',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '21',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '79',
                'name' => 'Wita Saraswati',
                'nik' => '3578046007640004',
                'photo' => 'user/photo/mMZzpySNfLaOhwjOCfPznRHiNZsLp1mTCUllt3u7.png',
                'phone' => '0818500396',
                'address' => 'Bengawan 41 RT 004/RW 002 Kel. Darmo, Kec. Wonokromo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'witaoesman@gmail.com',
                'email_verified_at' => '2024-09-26 06:46:02',
                'google_id' => null,
                'password' => '$2y$12$OwzsTNMs1EzDxxrlz/WUueIy5rC8KXRWDmwOlN8Pwwpu9S0hIwYOG',
                'remember_token' => null,
                'created_at' => '2024-09-26 06:41:24',
                'updated_at' => '2024-11-28 02:29:24',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '22',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '80',
                'name' => 'Agus Sulistyono',
                'nik' => '3578092708600004',
                'photo' => 'user/photo/jOqHdBuuSxpSsAbeLfNinCn4Jx379IyjQJjXNQi3.png',
                'phone' => '082131413160',
                'address' => 'Manyar Tirtosari 4/24 RT 002/RW 007, Kel. Klampis Ngasem, Kec. Sukolilo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'agus.sulistyono@fk.unair.ac.id',
                'email_verified_at' => '2024-09-26 06:46:05',
                'google_id' => null,
                'password' => '$2y$12$YS8DwJFwzA5CCCAknEXUx.rc6sj.FPGHVmLw/34Zj8bSw50OmAq..',
                'remember_token' => null,
                'created_at' => '2024-09-26 06:43:12',
                'updated_at' => '2024-11-28 01:43:06',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '23',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '81',
                'name' => 'Budi Santoso',
                'nik' => '196302171989111001',
                'photo' => 'user/photo/tK2Bwb8eg35bDskKQyTH7kX9WsQpiPufa8D9Q3yU.png',
                'phone' => '08123581706',
                'address' => 'Jl. Manyar Indah X/19 Surabaya-60118',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'busobg98@yahoo.com',
                'email_verified_at' => '2024-09-26 06:46:09',
                'google_id' => null,
                'password' => '$2y$12$IUTvGMXaYPXmT8cNYYZYl.W37NuOQHcemG4HkjSEiFd.eOT85b1Iu',
                'remember_token' => null,
                'created_at' => '2024-09-26 06:45:20',
                'updated_at' => '2024-11-28 02:22:54',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '24',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '82',
                'name' => 'Brahmana Askandar Tjokroprawiro',
                'nik' => '3578021405730002',
                'photo' => 'user/photo/Nab7gMvgDUjGOwu6f6Z4uf6E3IteqlOAa8KTODlw.png',
                'phone' => '0811958080',
                'address' => 'Prof. Dr. Moestopo (Dharmahusada) 162 RT 005/ RW 004 Kel. Mojo, Kec. Gubeng, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'brahmanaaskandar@fk.unair.ac.id',
                'email_verified_at' => '2024-09-27 02:03:09',
                'google_id' => null,
                'password' => '$2y$12$ddtmvBEf/QdeON.W3aR8AOnonV0pfh0p9ipJU0KkJPL2hXSqA2w.q',
                'remember_token' => null,
                'created_at' => '2024-09-27 02:00:43',
                'updated_at' => '2024-12-06 02:34:28',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '25',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '83',
                'name' => 'Baksono Winardi',
                'nik' => '3515183009540001',
                'photo' => 'user/photo/KMPjrIRy6yDSU1wHwL2z1qaSB61bTS5v6gYBLBRo.png',
                'phone' => '08123410586',
                'address' => 'Jl. Palem Timur MD-112 RT 003/RW 008 Kel. Wadungasri, Kec. Waru, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'bakso_dr@yahoo.com',
                'email_verified_at' => '2024-09-27 02:27:37',
                'google_id' => null,
                'password' => '$2y$12$EtyhdFYZhrEyAUptfJDFSeJAj1EitVTP6AlAuBcYvCclOxIAqyQJm',
                'remember_token' => null,
                'created_at' => '2024-09-27 02:27:26',
                'updated_at' => '2024-12-06 02:39:39',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '26',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '84',
                'name' => 'Ashon Sa\'adi',
                'nik' => '3578082412670002',
                'photo' => 'user/photo/n28rylqYzsaGGPkI9qSvsNsgK1XlklsUHjkduye4.png',
                'phone' => '08170121121',
                'address' => 'Pucang Sewu 20 RT 002/RW 009, Kel. Pucang Sewu, Kec. Gubeng, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'ashontanti@gmail.com',
                'email_verified_at' => '2024-09-27 02:32:06',
                'google_id' => null,
                'password' => '$2y$12$p.G6BFIduuzNvWDw4eC.fu6oy/Y3yKJJYLtWsBBbhKpUF28XjWDTi',
                'remember_token' => null,
                'created_at' => '2024-09-27 02:29:13',
                'updated_at' => '2024-12-06 02:41:12',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '27',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '85',
                'name' => 'Relly Yanuari Primariawan',
                'nik' => '196901281999031003',
                'photo' => 'user/photo/syfZOVBBJqyiVoz0Vk6nhtFL5O1GZDIH1LrKZZjt.png',
                'phone' => '08123020492',
                'address' => 'Jl. Komplek San Diego M5/23 Pakuwon City Surabaya, Kel. Kalisari, Kec. Mulyorejo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'relly.yp@gmail.com',
                'email_verified_at' => '2024-09-27 02:32:10',
                'google_id' => null,
                'password' => '$2y$12$4kJNSM8SLm/.fAIJMddsBeHVH7iKGMaOgB24N7Ky8iKjH5ilGyb1G',
                'remember_token' => null,
                'created_at' => '2024-09-27 02:31:07',
                'updated_at' => '2024-12-06 02:40:24',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '28',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '86',
                'name' => 'Sri Ratna Dwiningsih',
                'nik' => '197308281999032002',
                'photo' => 'user/photo/CARLWXyfMNaUmfYkDDKojLnd6XX9V0ZX5vw9eUIS.png',
                'phone' => '08123219681',
                'address' => 'Jl. Baskara Tengah D/31 Surabaya 60112',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'sri-r-d@fk.unair.ac.id',
                'email_verified_at' => '2024-09-27 02:32:14',
                'google_id' => null,
                'password' => '$2y$12$AfUA1EwPXr1cQvq27v/sUudleOmrZJ9goCKAt1RMRB0SE/VyMyXZq',
                'remember_token' => null,
                'created_at' => '2024-09-27 02:31:53',
                'updated_at' => '2024-12-06 02:36:50',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '29',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '87',
                'name' => 'Budi Prasetyo',
                'nik' => '3578240305760001',
                'photo' => 'user/photo/vSyPLFQeJyfMcSY5P0kAhykNKVXOMt9pXqNLWwYv.png',
                'phone' => '081553019486',
                'address' => 'Kendangsari YKP Blok R/2 RT 007, RW 002, Kel. Kendangsari, Kec. Tenggilis Mejoyo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'budi-p@fk.unair.ac.id',
                'email_verified_at' => '2024-09-27 02:55:09',
                'google_id' => null,
                'password' => '$2y$12$QrQ/mbF9jxcKtC2jU8ifmu/npfT5w5YeKKSExPJKaSSDSap6eIuxm',
                'remember_token' => null,
                'created_at' => '2024-09-27 02:50:40',
                'updated_at' => '2024-12-06 02:42:06',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '30',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '88',
                'name' => 'Indra Yuliati',
                'nik' => '3515184407750005',
                'photo' => 'user/photo/zuhrH4JtXJZx0PeEohnpp66QBtVzyDhebwfvqH0q.png',
                'phone' => '0818514046',
                'address' => 'Jl. Dempo DE-20 RT 004/RW 008 Kel. Kepuh Kiriman, Kec. Waru, Kab. SIdoarjo',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'indrayuliatialif@yahoo.com',
                'email_verified_at' => '2024-09-27 02:55:12',
                'google_id' => null,
                'password' => '$2y$12$.XaRjiCz78ojpt4pP7en6uu2F3BGr7wvtB726mnFDMlCZRWNcLUSK',
                'remember_token' => null,
                'created_at' => '2024-09-27 02:52:56',
                'updated_at' => '2024-12-09 03:06:00',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '31',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '89',
                'name' => 'Gatut Hardianto',
                'nik' => '3578091910620003',
                'photo' => 'user/photo/wyi0hAedwIHTMSuwyUk6SPRe85td0ZHBskZsC1Na.png',
                'phone' => '0811589767',
                'address' => 'Baratajaya 4/82 RT 002/RW 005 Kel. Baratajaya, Kec. Gubeng, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'gatuthardianto62@gmail.com',
                'email_verified_at' => '2024-09-27 02:55:16',
                'google_id' => null,
                'password' => '$2y$12$IywdeIX7HSgk2T5a6vuomu.uNpw8AihJR3zohvMEV.kKWMpeVAph.',
                'remember_token' => null,
                'created_at' => '2024-09-27 02:53:50',
                'updated_at' => '2024-12-09 03:05:15',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '32',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '90',
                'name' => 'Eighty Mardiyan Kurniawati',
                'nik' => '3578065408770006',
                'photo' => 'user/photo/KLB6qcIbtVm5GQIiWRIYNii8E6lvmb2eq3zPfKLI.png',
                'phone' => '08113534449',
                'address' => 'Petemon 4/162-G RT 004/RW 014 Kel. Petemon, Kec. Sawahan, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'eighty-m-k@fk.unair.ac.id',
                'email_verified_at' => '2024-09-27 02:55:19',
                'google_id' => null,
                'password' => '$2y$12$rZGJwqTqDzLY//u5RBiLte/JPLBH4LkLx9YKBNA25OMM9RhBUwbx6',
                'remember_token' => null,
                'created_at' => '2024-09-27 02:54:40',
                'updated_at' => '2024-12-09 03:07:37',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '33',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '91',
                'name' => 'Jimmy Yanuar Annas',
                'nik' => '197701202008011009',
                'photo' => 'user/photo/BYiypp9ciyeYNQrNFtY4oVppQDBnzrGezfjNnh47.png',
                'phone' => '08983844159',
                'address' => 'Jl. Ngagel Tama No.72-74 Surabaya. 60283',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'jimmyyanuar@fk.unair.ac.id',
                'email_verified_at' => '2024-09-27 02:55:23',
                'google_id' => null,
                'password' => '$2y$12$tZsqn0g9GMjcppxapdw1v.aPfPV4KMyecPPZyzBCCKanbg4J78SES',
                'remember_token' => null,
                'created_at' => '2024-09-27 02:54:47',
                'updated_at' => '2024-12-09 03:09:22',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '34',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '92',
                'name' => 'Ernawati',
                'nik' => '3578035607770004',
                'photo' => 'user/photo/YRRLYkF1nNcC9UOjhXrY5EwnM6cQL18RsBtWLBYK.png',
                'phone' => '081232850261',
                'address' => 'Virginia Regency E 2/3 Pakuwon City RT 006/RW 003, Kel. Kejawan Putih Tambak, Kec. Mulyorejo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'ernawati@fk.unair.ac.id',
                'email_verified_at' => '2024-09-27 02:55:26',
                'google_id' => null,
                'password' => '$2y$12$pqF1Iub.AKa1s4r/paYo/udjI/R236lJ8MIbMzAUEnFAojgiHCLs.',
                'remember_token' => null,
                'created_at' => '2024-09-27 02:54:54',
                'updated_at' => '2024-12-09 03:10:04',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '35',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '93',
                'name' => 'M. Ardian Cahya Laksana',
                'nik' => '3578090209740002',
                'photo' => 'user/photo/A2xOHqyGVNseeY2elGyf9vAUIVeHnxiJoduETvBo.png',
                'phone' => '08123056146',
                'address' => 'Galaxi Bumi Permai Blok M-3/20 RT 005, RW 005, Kel. Medokan Semampir, Kec. Sukolilo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'm.ardian@fk.unair.ac.id',
                'email_verified_at' => '2024-09-30 05:50:07',
                'google_id' => null,
                'password' => '$2y$12$qWe08a5rtHbBbM9tWiB9b.4lq3JBmPcHtBaEccGbRANTcm2Co9Pxa',
                'remember_token' => null,
                'created_at' => '2024-09-30 05:45:39',
                'updated_at' => '2024-12-10 03:48:27',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '36',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '94',
                'name' => 'M. Ilham Aldika Akbar',
                'nik' => '3578021801820001',
                'photo' => 'user/photo/w2FWj4gR01R7wVGlSgFHt5DSOI1SvPIA7ooxObFE.png',
                'phone' => '081703270900',
                'address' => 'Jemursari Utara V/8 RT 003/RW 008, Kel. Jemur Wonosari, Kec. Wonocolo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'dokter_aldi@yahoo.com',
                'email_verified_at' => '2024-09-30 05:50:10',
                'google_id' => null,
                'password' => '$2y$12$M2sqI8hoQfoJCW9d5HTeeuwMgxnHgldL9WVejwpjStQZ1IthUc.VG',
                'remember_token' => null,
                'created_at' => '2024-09-30 05:49:34',
                'updated_at' => '2024-12-10 03:50:42',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '37',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '95',
                'name' => 'Pungky Mulawardhana',
                'nik' => '3578080306810004',
                'photo' => 'user/photo/8nOOINoXP49geAUhjmfdGkzASUY7jMeloAO724ne.png',
                'phone' => '08123009606',
                'address' => 'Dharmahusada Indah A/28 RT 007/RW 004, Kel. Mojo, Kec. Gubeng, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'pungky.mulawardhana@gmail.com',
                'email_verified_at' => '2024-09-30 05:50:18',
                'google_id' => null,
                'password' => '$2y$12$vEXN8T3r115h4pIRYQ5Djuj9.VjHfiryNYdV54WpVolzfYNHSPf5S',
                'remember_token' => null,
                'created_at' => '2024-09-30 05:49:44',
                'updated_at' => '2024-12-10 03:51:36',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '38',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '96',
                'name' => 'Primandono Perbowo',
                'nik' => '3578030602780002',
                'photo' => 'user/photo/shmFzniJyAygqfmRsJqY6KSQ2cTuX3p0gs8Wr8DZ.png',
                'phone' => '081803360700',
                'address' => 'Sidosermo PDK 5 Kav 384 RT 002/RW 007, Kel. Sidosermo, Kec. Wonocolo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'primandonowondy1@gmail.com',
                'email_verified_at' => '2024-09-30 05:50:14',
                'google_id' => null,
                'password' => '$2y$12$nL53/00ZMWLa6O.0pBVaSeSWXsWeTVZKL8/p4xZTpteYL18Ci.KHe',
                'remember_token' => null,
                'created_at' => '2024-09-30 05:49:44',
                'updated_at' => '2024-12-10 03:52:42',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '39',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '97',
                'name' => 'Hari Nugroho',
                'nik' => '3578032405830002',
                'photo' => 'user/photo/YP8B8Ve18Ujw4ZmTKqypcxt5C1Y5hT42kEcK0EZ6.png',
                'phone' => '085755057550',
                'address' => 'Jl. Wisma Permai 1/99 RT 001/RW 005 Kel. Mulyorejo, Kec. Mulyorejo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'mail@harinugroho.com',
                'email_verified_at' => '2024-10-01 01:36:32',
                'google_id' => null,
                'password' => '$2y$12$EDID309lzbAAPc3rFyip.eUTDgDBHTMn6L8GKY3SmxYuHFtPt0WYq',
                'remember_token' => null,
                'created_at' => '2024-10-01 01:34:51',
                'updated_at' => '2024-11-18 05:33:26',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '40',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '98',
                'name' => 'Muhammad Yusuf',
                'nik' => '3516171010740007',
                'photo' => 'user/photo/5D9ehTMiszz9kj2mr8wrLbCYqbzRQLacUQlcEV7d.png',
                'phone' => '08121674373',
                'address' => 'Dupak Bandarejo 03/32-34 RT 007/RW 003, Kel. Dupak, Kec. Krembangan, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'dr.muhyusuf@gmail.com',
                'email_verified_at' => '2024-10-01 01:36:37',
                'google_id' => null,
                'password' => '$2y$12$sv9OjE/DiFaH9rTZpSRZN.NADDPgC0i1DTWm59dx/vZGtQYs1L5dm',
                'remember_token' => null,
                'created_at' => '2024-10-01 01:34:58',
                'updated_at' => '2024-11-18 05:32:43',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '41',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '99',
                'name' => 'M. Yohanes Ardianta Widyanugraha',
                'nik' => '198106242014031001',
                'photo' => 'user/photo/ZvsIAhnTQCDiGdBbsL3QQaIjBkzLAG8e5CekkJdl.png',
                'phone' => '085710544123',
                'address' => 'Galaxi Bumi Permai Blok L-3/52 Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'widyanugrahadr@yahoo.com',
                'email_verified_at' => '2024-10-01 01:36:42',
                'google_id' => null,
                'password' => '$2y$12$fG.hK1DCR3REPoJHYIMTS.sY1bYH6moVqpbhA4im4lFWrtMQ8BKAq',
                'remember_token' => null,
                'created_at' => '2024-10-01 01:35:03',
                'updated_at' => '2024-12-10 04:59:35',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '42',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '100',
                'name' => 'Manggala Pasca Wardhana',
                'nik' => '3578082011840005',
                'photo' => 'user/photo/iSZNrq1vpiD3gH9hag6tVkZbI3z9fHQYszM2v5OA.png',
                'phone' => '08123009505',
                'address' => 'Dharmahusada Indah A/28 RT 007/RW 004, Kel. Mojo, Kec. Gubeng, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'manggala.pasca@fk.unair.ac.id',
                'email_verified_at' => '2024-10-01 01:36:46',
                'google_id' => null,
                'password' => '$2y$12$ym.Ghb7kOheApiDLjTpDKevXcEmHFXb8PhHHCmkv15AiC2rt3DO/m',
                'remember_token' => null,
                'created_at' => '2024-10-01 01:35:09',
                'updated_at' => '2024-11-18 05:30:13',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '43',
                'deleted_by' => null,
                'education_level_id' => '3',
                'is_verified' => '1',
            ],
            [
                'id' => '101',
                'name' => 'Budi Wicaksono',
                'nik' => '3578020905780001',
                'photo' => 'user/photo/NTE1DroCn6g0x5ihF62HxsVfMnA4QRFhwmRLrBEp.png',
                'phone' => '0811320705',
                'address' => 'Galaxi Bumi Permai Blok J4/23 RT 002/RW 012, Kel. Semolowaru, Kec. Sukolilo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'budiobg@gmail.com',
                'email_verified_at' => '2024-10-01 05:37:05',
                'google_id' => null,
                'password' => '$2y$12$7mpZkFLr/zRAhlRj7E0ssehcbMtNYfPfJghWdwSzW/XBvhHFy1QMO',
                'remember_token' => null,
                'created_at' => '2024-10-01 05:36:54',
                'updated_at' => '2024-12-10 03:57:05',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '44',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '102',
                'name' => 'Khanisyah Erza Gumilar',
                'nik' => '3578210508840001',
                'photo' => 'user/photo/kIJphD7Tm5DfIWfB4rKafKMQDMdlrx5p3jjIlULE.png',
                'phone' => '081287940663',
                'address' => 'Bukit Pakis Utara 3/T.A 16 RT 001/RW 007, Kel. Dukuh Pakis, Kec. Dukuh Pakis, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'zkhankhanz@gmail.com',
                'email_verified_at' => '2024-10-02 02:02:51',
                'google_id' => null,
                'password' => '$2y$12$ATA8aoFxqHfVXAz60H7Yr.iJVNfPyvUoS9rWEI5PciCSxohsTwbq.',
                'remember_token' => null,
                'created_at' => '2024-10-02 01:50:52',
                'updated_at' => '2024-12-10 05:17:10',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '45',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '103',
                'name' => 'Hanifa Erlin Dharmayanti',
                'nik' => '3515184207840002',
                'photo' => 'user/photo/0LfjLjntBAZS0xcTum1r6FXUGHHfZMvm4A0zk6Bi.png',
                'phone' => '08123571740',
                'address' => 'Kalikepiting No.29-A RT 002/RW 005, Kel. Pacar Kembang, Kec. Tambak Sari, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'erlin.spog@gmail.com',
                'email_verified_at' => '2024-10-02 02:02:56',
                'google_id' => null,
                'password' => '$2y$12$pQUPXDrbaZkTMabW9KirJOjB.1HwiDQoy31i854kiF/4dE/lF.gke',
                'remember_token' => null,
                'created_at' => '2024-10-02 01:54:02',
                'updated_at' => '2024-11-12 04:54:21',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '46',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '104',
                'name' => 'Rizki Pranadyan',
                'nik' => '3578041006840005',
                'photo' => 'user/photo/un96RwDZGMdyXdOC5idJpyrG1IAWn0xFExJSaQpF.png',
                'phone' => '0811348623',
                'address' => 'Opak 27 RT 002/RW 001, Kel. Darmo, Kec. Wonokromo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'rizki.spog@gmail.com',
                'email_verified_at' => '2024-10-02 02:03:00',
                'google_id' => null,
                'password' => '$2y$12$zbbEtve4m1w3/5PF1TnL.OSa1zcgcxDvS1kDCl44ZFUQRBTFd5VdO',
                'remember_token' => null,
                'created_at' => '2024-10-02 01:59:45',
                'updated_at' => '2024-11-12 04:53:34',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '47',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '105',
                'name' => 'Arif Tunjungseto',
                'nik' => '3578030406850002',
                'photo' => 'user/photo/rObczs0vGSotFLUoGMuMARjuZEqLZonKtH0nHN27.png',
                'phone' => '08113307846',
                'address' => 'Regency 21-C-20 Jl. Arief Rakhman Hakim 138-142 C-20 RT 006/RW 004, Kel. Klampis Ngasem, Kec. Sukolilo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'tunjungseto@gmail.com',
                'email_verified_at' => '2024-10-02 02:03:05',
                'google_id' => null,
                'password' => '$2y$12$.R03Pjvyd6cW3g7vJrqGqeD1JPGsp9EFUCixlB108SSIejaUwD13u',
                'remember_token' => null,
                'created_at' => '2024-10-02 02:01:23',
                'updated_at' => '2024-11-12 04:52:37',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '48',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '106',
                'name' => 'Nareswari Imanadha Cininta M',
                'nik' => '3578265308860002',
                'photo' => 'user/photo/YMgUYfL1dMRMKwenrBp2XDcDwcg1Ry9QZbWvQFTk.png',
                'phone' => '081233721937',
                'address' => 'Bhaskara Selatan D-12 SBY RT 009/RW 002, Kel. Kalisari, Kec. Mulyorejo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'nareswari.cininta@gmail.com',
                'email_verified_at' => '2024-10-02 02:03:09',
                'google_id' => null,
                'password' => '$2y$12$JJBV1vRHcI4NI1PYSCVqcuffwLMmQ.mUZanIfHFxLqFR6hEIDD.I6',
                'remember_token' => null,
                'created_at' => '2024-10-02 02:02:39',
                'updated_at' => '2024-11-12 04:51:18',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '49',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '107',
                'name' => 'Birama Robby Indraprasta',
                'nik' => '3578260302850002',
                'photo' => 'user/photo/Ij0Rh9fd4IEq1GwGDpkevvj8DFOMm3LbjpJBI5kB.png',
                'phone' => '081335040100',
                'address' => 'Mulyosari BPD 43 SBY RT 002/RW 004, Kel. Kalisari, Kec. Mulyorejo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'birama.robby.in-2020@fk.unair.ac.id',
                'email_verified_at' => '2024-10-03 06:22:48',
                'google_id' => null,
                'password' => '$2y$12$cCKCUarzv8Oh/RolFQ9DZeOs95hDvjiDp712OmAmFfs5Blb4kZwqK',
                'remember_token' => null,
                'created_at' => '2024-10-03 06:21:24',
                'updated_at' => '2024-11-06 02:31:04',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '50',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '108',
                'name' => 'Tri Hastono',
                'nik' => '3578091402840003',
                'photo' => 'user/photo/7AdYAfsztXlOEzkRjiZgU2rgOaL60YUfz0qPpoQB.png',
                'phone' => '0811337366',
                'address' => 'Manyar Kartika 3/20 RT 003/RW 007, Kel. Menur Pumpungan, Kec. Sukolilo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'dr.trihastonosh@gmail.com',
                'email_verified_at' => '2024-10-03 06:22:51',
                'google_id' => null,
                'password' => '$2y$12$QqagfOoG71654cBRGw89EOthjU0iTR/ctfNN9EmB.RKXyrn5NTK5C',
                'remember_token' => null,
                'created_at' => '2024-10-03 06:21:29',
                'updated_at' => '2024-12-11 04:15:51',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '51',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '109',
                'name' => 'Soedarsono Hadipranata',
                'nik' => '3578180807840002',
                'photo' => 'user/photo/w6lV3a87LF2ON5HT6AO28uXB36pDepIV5nrvlaY7.png',
                'phone' => '081339307212',
                'address' => 'Kinibalu Barat I/7 RT 013/RW 018, Kel. Petemon, Kec. Sawahan, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'dr.soedarsono@gmail.com',
                'email_verified_at' => '2024-10-03 06:22:58',
                'google_id' => null,
                'password' => '$2y$12$Lj9t/dADIjpgXO.rGwC/feWPQav3N8XXSsSuan.9A37Z7TxRy22.a',
                'remember_token' => null,
                'created_at' => '2024-10-03 06:21:36',
                'updated_at' => '2024-11-06 02:28:29',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '53',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '110',
                'name' => 'Rozi Aditya Aryananda',
                'nik' => '3578262908850004',
                'photo' => 'user/photo/MR8RAMMgWUY7pyttlqxgMa8L5Vs6LJXWArS13IUr.png',
                'phone' => '082173999885',
                'address' => 'Jl. Wisma Permai Barat 2/MM-80 RT 002/RW 007, Kel. Mulyorejo, Kec. Mulyorejo, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'rozi.odi@gmail.com',
                'email_verified_at' => '2024-10-03 06:23:01',
                'google_id' => null,
                'password' => '$2y$12$wiIQp/X/LxfezKVxxkldqer57R2BOwVPC5igvM3zRZdPcePY8TlZO',
                'remember_token' => null,
                'created_at' => '2024-10-03 06:22:34',
                'updated_at' => '2024-11-06 02:21:59',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '54',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '111',
                'name' => 'Eccita Rahestiningtyas',
                'nik' => '3578055010870004',
                'photo' => 'user/photo/jSz7DuiXJL33u9gxvX9Ejm2I5QFs9750Dw7UJyh7.png',
                'phone' => '081330755662',
                'address' => 'Plemahan 3/22-24 RT 003/RW 010 Kel. Kedungdoro, Kec. Tegalsari, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'eccitarahes87@gmail.com',
                'email_verified_at' => '2024-10-04 05:50:07',
                'google_id' => null,
                'password' => '$2y$12$qkVfA33W.LL2XFpkIowrb.h.bfgMKNhrDni1NEY77OPt6BFfkqGw6',
                'remember_token' => null,
                'created_at' => '2024-10-04 05:43:41',
                'updated_at' => '2024-11-06 02:11:11',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '55',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '112',
                'name' => 'Khoirunnisa Novitasari',
                'nik' => '3578135211910001',
                'photo' => 'user/photo/cEoi0hW51CWAB7ntL7eFS5ILS8Zh6nEFR0FzK398.png',
                'phone' => '081330335987',
                'address' => 'Maspati 4/45 RT 004/RW 007, Kel. Bubutan, Kec. Bubutan, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'khoirunnisanovitasariunair@gmail.com',
                'email_verified_at' => '2024-10-04 05:50:12',
                'google_id' => null,
                'password' => '$2y$12$7Ugz0LmLGnYT6D7l.ZRR6uCmilhNgLWhr/iIoTy2i6dIbDGPhV/Iq',
                'remember_token' => null,
                'created_at' => '2024-10-04 05:46:29',
                'updated_at' => '2024-11-06 02:09:23',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '56',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '113',
                'name' => 'Riska Wahyuningtyas',
                'nik' => '3571016310900001',
                'photo' => 'user/photo/af2kIkwMDAWIIiUPQfgOzXOTlLLTqI5eIhDiulgX.png',
                'phone' => '081289839447',
                'address' => 'Wisma Bungurasih GG II/72 RT 004/RW 005, Kel. Bungurasih, Kec. Waru, Kabupaten Sidoarjo',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'riska.wahyuningtyas23@gmail.com',
                'email_verified_at' => '2024-10-04 05:50:17',
                'google_id' => null,
                'password' => '$2y$12$9DlkIW6EDEpNKNju8XloUeuF0WuqsPLBf1206quQrLGbCaDp40lKe',
                'remember_token' => null,
                'created_at' => '2024-10-04 05:48:40',
                'updated_at' => '2024-11-05 06:54:47',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '57',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '114',
                'name' => 'Bayu Priangga',
                'nik' => '3578091111910002',
                'photo' => 'user/photo/4Ks0wfv6zgJzmctBxTikGekOP4lx09o9bMaz9ehO.png',
                'phone' => '082119911112',
                'address' => 'Medokan Asri Utara Blok R-24 RT 007/RW 008, Kel Medokan Ayu, Kec. Rungkut, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'bayupriangga@gmail.com',
                'email_verified_at' => '2024-10-04 05:50:21',
                'google_id' => null,
                'password' => '$2y$12$JFOxLhU0I6nIKK0QuuBLVO/XDCRGpDnYBkh2bJD0mZsv.hrEUJdbO',
                'remember_token' => null,
                'created_at' => '2024-10-04 05:49:38',
                'updated_at' => '2024-11-05 06:53:44',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '58',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '115',
                'name' => 'Qurrata Akyuni',
                'nik' => '7371145403900009',
                'photo' => 'user/photo/m8YZueL6G9OXkIJ5pAdBUjgj7sWzbdJyGILg5XKs.png',
                'phone' => '08113400305',
                'address' => 'Jojoran 1 Blok A/10 RT 001/RW 013, Kel Mojo, Kec. Gubeng, Kota Surabaya',
                'institution' => 'RSDS',
                'cv' => null,
                'email' => 'akyuniqurrata@gmail.com',
                'email_verified_at' => '2024-10-04 05:50:26',
                'google_id' => null,
                'password' => '$2y$12$fqT/3LLCR175CquGz2oSqutveqO0myKz87bWy74m.0N77HbteTmh6',
                'remember_token' => null,
                'created_at' => '2024-10-04 05:49:48',
                'updated_at' => '2024-11-05 06:46:38',
                'deleted_at' => null,
                'created_by' => '2',
                'updated_by' => '59',
                'deleted_by' => null,
                'education_level_id' => '2',
                'is_verified' => '1',
            ],
            [
                'id' => '116',
                'name' => 'Voluptas sed dolorem',
                'nik' => 'Qui totam quibus',
                'photo' => null,
                'phone' => 'Tempora cumqu',
                'address' => 'Assumenda numquam do',
                'institution' => 'Sint qui officia qui',
                'cv' => null,
                'email' => 'wowafyg@mailinator.com',
                'email_verified_at' => null,
                'google_id' => null,
                'password' => '$2y$12$Z.MqvmrlLOmefvijLXCtB.BGl1fRlEdJ/z8Fv1QE7DlMaF9alm2Pi',
                'remember_token' => null,
                'created_at' => '2025-01-04 18:47:09',
                'updated_at' => '2025-01-04 18:47:09',
                'deleted_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'education_level_id' => '4',
                'is_verified' => '1',
            ],
        ];

        foreach ($users as $user) {
            User::create($user);
        }

        // Seed roles
        $roles = [
            ['id' => '2', 'name' => 'admin', 'guard_name' => 'web', 'created_at' => null, 'updated_at' => null],
            ['id' => '3', 'name' => 'lecturer', 'guard_name' => 'web', 'created_at' => null, 'updated_at' => null],
            ['id' => '4', 'name' => 'participant', 'guard_name' => 'web', 'created_at' => null, 'updated_at' => null],
        ];

        foreach ($roles as $role) {
            Role::create($role);
        }

        // Seed model has roles
        $modelHasRoles = [
            ['role_id' => '2', 'model_type' => 'App\\Models\\User', 'model_id' => '2'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '3'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '8'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '68'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '69'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '70'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '71'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '72'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '73'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '74'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '75'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '76'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '77'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '78'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '79'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '80'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '81'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '82'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '83'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '84'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '85'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '86'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '87'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '88'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '89'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '90'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '91'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '92'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '93'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '94'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '95'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '96'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '97'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '98'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '99'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '100'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '101'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '102'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '103'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '104'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '105'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '106'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '107'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '108'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '109'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '110'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '111'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '112'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '113'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '114'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '115'],
            ['role_id' => '3', 'model_type' => 'App\\Models\\User', 'model_id' => '116'],
            ['role_id' => '4', 'model_type' => 'App\\Models\\User', 'model_id' => '10'],
            ['role_id' => '4', 'model_type' => 'App\\Models\\User', 'model_id' => '11'],
            ['role_id' => '4', 'model_type' => 'App\\Models\\User', 'model_id' => '12'],
            ['role_id' => '4', 'model_type' => 'App\\Models\\User', 'model_id' => '13'],
        ];

        foreach ($modelHasRoles as $modelHasRole) {
            DB::table('model_has_roles')->insert($modelHasRole);
        }

        // Seed topics
        $topics = [
            ['id' => '2', 'name' => 'Topic 2', 'created_at' => '2024-12-25 22:43:18', 'updated_at' => '2024-12-25 22:43:18', 'deleted_at' => null, 'created_by' => '14', 'updated_by' => '14', 'deleted_by' => null],
            ['id' => '3', 'name' => 'Topic 1', 'created_at' => '2024-12-25 22:58:36', 'updated_at' => '2024-12-25 22:58:36', 'deleted_at' => null, 'created_by' => '2', 'updated_by' => '2', 'deleted_by' => null],
        ];

        foreach ($topics as $topic) {
            Topic::create($topic);
        }

        DB::commit();
    }
}
